# Generated by Django 6.0.4 on 2026-05-07 14:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_seguro', models.BooleanField(default=False)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ajuste de Sistema',
                'verbose_name_plural': 'Ajustes de Sistema',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('area_especifica', models.CharField(blank=True, max_length=150, null=True, verbose_name='Área Institucional')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InventarioCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('cantidad_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador'), ('activos', 'Encargado de Activos'), ('bienes', 'Bienes y Servicios'), ('chofer', 'Chofer')], default='chofer', max_length=20)),
                ('ci', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('licencia_conducir', models.CharField(blank=True, max_length=20, null=True)),
                ('vencimiento_licencia', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.area')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Peaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='peajes/')),
                ('chofer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValeCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_vale', models.CharField(max_length=50, unique=True)),
                ('cantidad_litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_bs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='vales/')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField(default=2024, verbose_name='Año')),
                ('tipo', models.CharField(help_text='Ej: Vagoneta, Camioneta', max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('capacidad_tanque', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nro_chasis', models.CharField(max_length=50, unique=True)),
                ('kilometraje_actual', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('operacional', 'ACTIVO'), ('mantenimiento', 'EN MANTENIMIENTO'), ('inactivo', 'INACTIVO')], default='operacional', max_length=20)),
                ('rendimiento_km_litro', models.DecimalField(decimal_places=2, default=5.0, help_text='KM por Litro', max_digits=5)),
                ('tipo_combustible', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel')], default='Gasolina', max_length=20)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.area')),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('reporte_cerrado', models.BooleanField(default=False)),
                ('estado_viaje', models.CharField(choices=[('en_curso', 'En Curso'), ('finalizado', 'Finalizado')], default='finalizado', max_length=20)),
                ('estado_validacion', models.CharField(choices=[('pendiente', 'PENDIENTE'), ('validado', 'VALIDADO'), ('rechazado', 'RECHAZADO'), ('anomalia', 'ANOMALÍA')], default='pendiente', max_length=20)),
                ('observacion_admin', models.TextField(blank=True, null=True, verbose_name='Observación de Auditoría')),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('hora_llegada', models.TimeField(blank=True, null=True)),
                ('responsable_viaje', models.CharField(blank=True, max_length=150, null=True)),
                ('origen', models.CharField(default='Potosí', max_length=150)),
                ('terreno', models.CharField(choices=[('plano', 'Plano'), ('montana', 'Montaña'), ('mixto', 'Mixto')], default='plano', max_length=20)),
                ('carga', models.CharField(choices=[('ligera', 'Ligera'), ('pesada', 'Pesada')], default='ligera', max_length=20)),
                ('tipo_ruta', models.CharField(choices=[('Urbana', 'Urbana'), ('Interprovincial', 'Interprovincial'), ('Rural', 'Rural'), ('Mixta', 'Mixta')], default='Urbana', max_length=20)),
                ('distancia_estimada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('km_inicial', models.PositiveIntegerField(default=0)),
                ('km_final', models.PositiveIntegerField(default=0)),
                ('destino', models.CharField(max_length=255)),
                ('objetivo_comision', models.TextField(verbose_name='Objetivo de la comisión')),
                ('nro_vale_combustible', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nro. de Vale')),
                ('cantidad_litros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo en Bs.')),
                ('nro_factura', models.CharField(default='S/N', max_length=50)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('nro_memorandum', models.CharField(max_length=50, verbose_name='Nro de Memorándum')),
                ('documento_acta', models.FileField(blank=True, null=True, upload_to='actas/')),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('motivo_baja', models.CharField(blank=True, max_length=255, null=True)),
                ('documento_baja', models.FileField(blank=True, null=True, upload_to='bajas/')),
                ('chofer', models.ForeignKey(limit_choices_to={'rol': 'chofer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('tipo_ruta', models.CharField(choices=[('Urbana', 'Urbana'), ('Interprovincial', 'Interprovincial'), ('Rural', 'Rural'), ('Mixta', 'Mixta')], max_length=20)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('km_inicio', models.PositiveIntegerField()),
                ('km_fin', models.PositiveIntegerField()),
                ('motivo', models.CharField(max_length=255)),
                ('distancia_real', models.PositiveIntegerField(editable=False)),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='gestion.bitacora')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.FloatField()),
                ('tiempo_horas', models.FloatField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_destino', to='gestion.ciudad')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_origen', to='gestion.ciudad')),
            ],
            options={
                'unique_together': {('origen', 'destino')},
            },
        ),
    ]
