# Generated by Django 6.0.4 on 2026-06-20 16:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_seguro', models.BooleanField(default=False)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ajuste de Sistema',
                'verbose_name_plural': 'Ajustes de Sistema',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('area_especifica', models.CharField(blank=True, max_length=150, null=True, verbose_name='Área Institucional')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Activo')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('cantidad_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('categoria_licencia', models.CharField(blank=True, choices=[('B', 'Categoría B'), ('C', 'Categoría C')], max_length=2, null=True)),
                ('rol', models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador'), ('activos', 'Encargado de Activos'), ('chofer', 'Chofer')], default='chofer', max_length=20)),
                ('ci', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('licencia_conducir', models.CharField(blank=True, max_length=20, null=True)),
                ('vencimiento_licencia', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('motivo_baja', models.TextField(blank=True, null=True)),
                ('ultima_actividad', models.DateTimeField(blank=True, null=True)),
                ('baja_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_desactivados', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.area')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('reporte_cerrado', models.BooleanField(default=False)),
                ('documento_enmienda', models.FileField(blank=True, null=True, upload_to='enmiendas/', verbose_name='Documento de Respaldo de Enmienda')),
                ('estado_viaje', models.CharField(choices=[('en_curso', 'En Curso'), ('finalizado', 'Finalizado')], default='finalizado', max_length=20)),
                ('estado_validacion', models.CharField(choices=[('pendiente', 'PENDIENTE'), ('validado', 'VALIDADO'), ('rechazado', 'RECHAZADO'), ('anomalia', 'ANOMALÍA')], default='validado', max_length=20)),
                ('solicitud_correccion', models.BooleanField(default=False)),
                ('motivo_correccion', models.TextField(blank=True, null=True)),
                ('observacion_admin', models.TextField(blank=True, null=True, verbose_name='Observación de Auditoría')),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('hora_llegada', models.TimeField(blank=True, null=True)),
                ('responsable_viaje', models.CharField(blank=True, max_length=150, null=True)),
                ('origen', models.CharField(default='Potosí', max_length=150)),
                ('terreno', models.CharField(choices=[('plano', 'Plano'), ('montana', 'Montaña'), ('mixto', 'Mixto')], default='plano', max_length=20)),
                ('carga', models.CharField(choices=[('ligera', 'Ligera'), ('pesada', 'Pesada')], default='ligera', max_length=20)),
                ('tipo_ruta', models.CharField(choices=[('Urbana', 'Urbana'), ('Interprovincial', 'Interprovincial'), ('Rural', 'Rural'), ('Mixta', 'Mixta')], default='Urbana', max_length=20)),
                ('distancia_estimada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('km_inicial', models.PositiveIntegerField(default=0)),
                ('km_final', models.PositiveIntegerField(default=0)),
                ('destino', models.CharField(max_length=255)),
                ('objetivo_comision', models.TextField(verbose_name='Objetivo de la comisión')),
                ('nro_vale_combustible', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nro. de Vale')),
                ('cantidad_litros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo en Bs.')),
                ('nro_factura', models.CharField(default='S/N', max_length=50)),
                ('estacion_servicio', models.CharField(blank=True, max_length=150, null=True, verbose_name='Estación de Servicio')),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('combustible_utilizado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rendimiento_aplicado', models.DecimalField(decimal_places=2, default=6.0, max_digits=5)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BitacoraActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario_texto', models.CharField(blank=True, max_length=150, null=True)),
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(choices=[('seguridad', 'SEGURIDAD / ACCESO'), ('operativo', 'OPERACIÓN DIARIA'), ('auditoria', 'AUDITORÍA / REPORTES'), ('sistema', 'SISTEMA / BACKUP'), ('error', 'ERROR DE SISTEMA')], max_length=20)),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora de Actividad',
                'verbose_name_plural': 'Bitácora de Actividades',
            },
        ),
        migrations.CreateModel(
            name='JustificacionEdicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla_afectada', models.CharField(max_length=50)),
                ('registro_id', models.PositiveIntegerField()),
                ('motivo', models.TextField(verbose_name='Motivo de la corrección')),
                ('documento_respaldo', models.FileField(upload_to='correcciones/%Y/%m/', verbose_name='Nota de Respaldo (PDF/JPG/PNG)')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('observacion_adicional', models.TextField(blank=True, null=True)),
                ('superusuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(blank=True, max_length=150)),
                ('rol', models.CharField(blank=True, max_length=50)),
                ('accion', models.CharField(choices=[('login_exitoso', 'Inicio de Sesión'), ('login_fallido', 'Intento Fallido'), ('logout', 'Cierre de Sesión'), ('creacion', 'Creación de Registro'), ('modificacion', 'Cambio de Datos'), ('eliminacion', 'Baja Lógica'), ('reporte', 'Generación de Reporte'), ('backup', 'Descarga de Backup'), ('error', 'Error de Sistema')], max_length=20)),
                ('tabla', models.CharField(blank=True, max_length=100)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('valor_anterior', models.JSONField(blank=True, null=True)),
                ('valor_nuevo', models.JSONField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Peaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='peajes/')),
                ('chofer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudEdicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_correccion', models.TextField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='gestion.bitacora')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValeCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_vale', models.CharField(max_length=50, unique=True)),
                ('cantidad_litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_bs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='vales/')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='vehiculos/', verbose_name='Fotografía del Vehículo')),
                ('vencimiento_soat', models.DateField(blank=True, null=True, verbose_name='Vencimiento SOAT')),
                ('placa', models.CharField(max_length=15, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField(default=2024, verbose_name='Año')),
                ('tipo', models.CharField(help_text='Ej: Vagoneta, Camioneta', max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('capacidad_tanque', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nro_chasis', models.CharField(max_length=50, unique=True)),
                ('kilometraje_actual', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('operacional', 'ACTIVO'), ('mantenimiento', 'EN MANTENIMIENTO'), ('inactivo', 'INACTIVO')], default='operacional', max_length=20)),
                ('rendimiento_km_litro', models.DecimalField(decimal_places=2, default=5.0, help_text='KM por Litro', max_digits=5)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.area')),
                ('tipo_combustible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='gestion.tipocombustible')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida Real')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo del Mantenimiento')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('encargado_taller', models.CharField(blank=True, max_length=150, null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='gestion.vehiculo')),
            ],
            options={
                'verbose_name': 'Registro de Mantenimiento',
                'verbose_name_plural': 'Registros de Mantenimiento',
            },
        ),
        migrations.AddField(
            model_name='bitacora',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.vehiculo'),
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('nro_memorandum', models.CharField(max_length=50, verbose_name='Nro de Memorándum')),
                ('documento_acta', models.FileField(blank=True, null=True, upload_to='actas/')),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('motivo_baja', models.CharField(blank=True, max_length=255, null=True)),
                ('documento_baja', models.FileField(blank=True, null=True, upload_to='bajas/')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.area', verbose_name='Secretaría en ese periodo')),
                ('chofer', models.ForeignKey(limit_choices_to={'rol': 'chofer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('tipo_ruta', models.CharField(choices=[('Urbana', 'Urbana'), ('Interprovincial', 'Interprovincial'), ('Rural', 'Rural'), ('Mixta', 'Mixta')], max_length=20)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('km_inicio', models.PositiveIntegerField()),
                ('km_fin', models.PositiveIntegerField()),
                ('motivo', models.CharField(max_length=255)),
                ('distancia_real', models.PositiveIntegerField(editable=False)),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='gestion.bitacora')),
            ],
        ),
    ]
