# Generated by Django 6.0.4 on 2026-05-08 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida Real')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo del Mantenimiento')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('encargado_taller', models.CharField(blank=True, max_length=150, null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='gestion.vehiculo')),
            ],
            options={
                'verbose_name': 'Registro de Mantenimiento',
                'verbose_name_plural': 'Registros de Mantenimiento',
            },
        ),
    ]
