# Generated by Django 6.0.4 on 2026-06-21 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='combustible_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Litros Iniciales en Tanque'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_actualizacion_rendimiento',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Última actualización de rendimiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='rendimiento_km_litro',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=5, verbose_name='Rendimiento KM/L (Constante Matriz)'),
        ),
    ]
