# Generated by Django 6.0.4 on 2026-04-16 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('capacidad_tanque', models.DecimalField(decimal_places=2, help_text='En litros o galones', max_digits=10)),
                ('estado', models.CharField(choices=[('operacional', 'OPERACIONAL'), ('mantenimiento', 'MANTENIMIENTO'), ('fuera_servicio', 'FUERA DE SERVICIO')], default='operacional', max_length=20)),
                ('tipo_vehiculo', models.CharField(help_text='Ej: Camioneta, Vagoneta, Bus', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('memo_referencia', models.CharField(max_length=100, verbose_name='Número de Memorándum')),
                ('acta_entrega', models.FileField(blank=True, null=True, upload_to='actas/')),
                ('activo', models.BooleanField(default=True)),
                ('chofer', models.ForeignKey(limit_choices_to={'rol': 'chofer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.vehiculo')),
            ],
        ),
    ]
