# Generated by Django 6.0.4 on 2026-04-17 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_vehiculo_asignacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion',
            old_name='acta_entrega',
            new_name='documento_acta',
        ),
        migrations.RenameField(
            model_name='asignacion',
            old_name='activo',
            new_name='esta_activo',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='memo_referencia',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='capacidad_tanque',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='tipo_vehiculo',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='nro_memorandum',
            field=models.CharField(default='', max_length=50, verbose_name='Nro de Memorándum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='licencia_conducir',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='vencimiento_licencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='nro_chasis',
            field=models.CharField(default='0', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(default='', help_text='Ej: Vagoneta, Camioneta', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('km_inicial', models.PositiveIntegerField()),
                ('km_final', models.PositiveIntegerField()),
                ('destino', models.CharField(max_length=255)),
                ('objetivo_comision', models.TextField(verbose_name='Objetivo de la comisión')),
                ('nro_vale_combustible', models.CharField(max_length=50, verbose_name='Nro. de Vale')),
                ('cantidad_litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo en Bs.')),
                ('nro_factura', models.CharField(max_length=50)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.vehiculo')),
            ],
        ),
    ]
