# Generated by Django 6.0.4 on 2026-05-08 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_registromantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.area', verbose_name='Secretaría en ese periodo'),
        ),
    ]
