# Generated by Django 6.0.4 on 2026-04-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_rename_acta_entrega_asignacion_documento_acta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('cantidad_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='bitacora',
            name='estado_validacion',
            field=models.CharField(choices=[('pendiente', 'PENDIENTE'), ('validado', 'VALIDADO'), ('rechazado', 'RECHAZADO')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel')], default='Gasolina', max_length=20),
        ),
    ]
