# Generated by Django 6.0.4 on 2026-06-26 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_vehiculo_combustible_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('periodo', models.CharField(max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Folio de Reporte',
                'verbose_name_plural': 'Folios de Reportes',
            },
        ),
    ]
