# Generated by Django 6.0.4 on 2026-06-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_reportefolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportefolio',
            options={},
        ),
        migrations.AlterField(
            model_name='reportefolio',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='reportefolio',
            constraint=models.UniqueConstraint(fields=('numero', 'periodo'), name='unique_reporte_periodo'),
        ),
    ]
