# Generated by Django 6.0.4 on 2026-04-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_inventariocombustible_bitacora_estado_validacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='estado_validacion',
            field=models.CharField(choices=[('pendiente', 'PENDIENTE'), ('validado', 'VALIDADO'), ('rechazado', 'RECHAZADO'), ('animalia', 'ANOMALÍA')], default='pendiente', max_length=20),
        ),
    ]
