# Generated by Django 6.0.4 on 2026-04-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_area_tipocombustible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_seguro', models.BooleanField(default=False)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ajuste de Sistema',
                'verbose_name_plural': 'Ajustes de Sistema',
            },
        ),
    ]
