# Generated by Django 6.0.4 on 2026-05-13 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_logauditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario_texto', models.CharField(blank=True, max_length=150, null=True)),
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(choices=[('seguridad', 'SEGURIDAD / ACCESO'), ('operativo', 'OPERACIÓN DIARIA'), ('auditoria', 'AUDITORÍA / REPORTES'), ('sistema', 'SISTEMA / BACKUP'), ('error', 'ERROR DE SISTEMA')], max_length=20)),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora de Actividad',
                'verbose_name_plural': 'Bitácora de Actividades',
            },
        ),
        migrations.CreateModel(
            name='JustificacionEdicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla_afectada', models.CharField(max_length=50)),
                ('registro_id', models.PositiveIntegerField()),
                ('motivo', models.TextField(verbose_name='Motivo de la corrección')),
                ('documento_respaldo', models.FileField(upload_to='correcciones/%Y/%m/', verbose_name='Nota de Respaldo (PDF/JPG/PNG)')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('observacion_adicional', models.TextField(blank=True, null=True)),
                ('superusuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
