# Generated by Django 6.0.4 on 2026-05-13 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_bitacoraactividad_justificacionedicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logauditoria',
            name='objeto_id',
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='rol',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='usuario_nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='accion',
            field=models.CharField(choices=[('login_exitoso', 'Inicio de Sesión'), ('login_fallido', 'Intento Fallido'), ('logout', 'Cierre de Sesión'), ('creacion', 'Creación de Registro'), ('modificacion', 'Cambio de Datos'), ('eliminacion', 'Baja Lógica'), ('reporte', 'Generación de Reporte'), ('backup', 'Descarga de Backup'), ('error', 'Error de Sistema')], max_length=20),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='tabla',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
