# Generated by Django 6.0.4 on 2026-04-20 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_ajustesistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.area'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='rendimiento_km_litro',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='KM por Litro', max_digits=5),
        ),
    ]
