# Generated by Django 6.0.4 on 2026-04-26 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_vehiculo_area_vehiculo_rendimiento_km_litro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('tipo_ruta', models.CharField(choices=[('Urbana', 'Urbana'), ('Interprovincial', 'Interprovincial'), ('Rural', 'Rural'), ('Mixta', 'Mixta')], max_length=20)),
                ('km_inicio', models.PositiveIntegerField()),
                ('km_fin', models.PositiveIntegerField()),
                ('motivo', models.CharField(max_length=255)),
                ('distancia_real', models.PositiveIntegerField(editable=False)),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='gestion.bitacora')),
            ],
        ),
        migrations.CreateModel(
            name='Peaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='peajes/')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peajes', to='gestion.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.FloatField()),
                ('tiempo_horas', models.FloatField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_destino', to='gestion.ciudad')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_origen', to='gestion.ciudad')),
            ],
            options={
                'unique_together': {('origen', 'destino')},
            },
        ),
    ]
