# Generated by Django 6.0.4 on 2026-05-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_remove_logauditoria_objeto_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultima_actividad',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
