# Generated by Django 6.0.4 on 2026-05-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_usuario_ultima_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
