# Generated by Django 6.0.4 on 2026-04-26 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_ciudad_viaje_peaje_ruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValeCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_vale', models.CharField(max_length=50, unique=True)),
                ('cantidad_litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_bs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='vales/')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
