# Generated by Django 6.0.4 on 2026-05-25 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_vehiculo_tipo_combustible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='gestion.tipocombustible'),
        ),
    ]
