# Generated by Django 6.0.4 on 2026-04-28 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_valecombustible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peaje',
            name='viaje',
        ),
        migrations.AddField(
            model_name='peaje',
            name='chofer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peaje',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
