# Generated by Django 6.0.4 on 2026-04-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_remove_peaje_viaje_peaje_chofer_peaje_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='hora_llegada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='responsable_viaje',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
