# Generated by Django 6.0.4 on 2026-05-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='categoria_licencia',
            field=models.CharField(blank=True, choices=[('A', 'Categoría A'), ('B', 'Categoría B')], max_length=2, null=True, verbose_name='Categoría de Licencia'),
        ),
    ]
