# Generated by Django 6.0.4 on 2026-04-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_bitacora_hora_llegada_bitacora_hora_salida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='estado_viaje',
            field=models.CharField(choices=[('en_curso', 'En Curso'), ('finalizado', 'Finalizado')], default='finalizado', max_length=20),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='cantidad_litros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo en Bs.'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='estado_validacion',
            field=models.CharField(choices=[('pendiente', 'PENDIENTE'), ('validado', 'VALIDADO'), ('rechazado', 'RECHAZADO'), ('anomalia', 'ANOMALÍA')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='km_final',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='km_inicial',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='nro_factura',
            field=models.CharField(default='S/N', max_length=50),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='nro_vale_combustible',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nro. de Vale'),
        ),
    ]
