# Generated by Django 6.0.4 on 2026-04-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_bitacora_estado_viaje_alter_bitacora_cantidad_litros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='distancia_estimada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='origen',
            field=models.CharField(default='Potosí', max_length=150),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='tipo_ruta',
            field=models.CharField(choices=[('Urbana', 'Urbana'), ('Interprovincial', 'Interprovincial'), ('Rural', 'Rural'), ('Mixta', 'Mixta')], default='Urbana', max_length=20),
        ),
    ]
