# Generated by Django 6.0.4 on 2026-04-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_bitacora_distancia_estimada_bitacora_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='carga',
            field=models.CharField(choices=[('ligera', 'Ligera'), ('pesada', 'Pesada')], default='ligera', max_length=20),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='terreno',
            field=models.CharField(choices=[('plano', 'Plano'), ('montana', 'Montaña'), ('mixto', 'Mixto')], default='plano', max_length=20),
        ),
    ]
