# Generated by Django 6.0.4 on 2026-04-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_bitacora_carga_bitacora_terreno'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='observacion_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Observación de Auditoría'),
        ),
    ]
