# Generated by Django 6.0.4 on 2026-06-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_alter_usuario_categoria_licencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='categoria_licencia',
            field=models.CharField(blank=True, choices=[('B', 'Categoría B'), ('C', 'Categoría C')], max_length=2, null=True, verbose_name='Categoría de Licencia'),
        ),
    ]
