# Generated by Django 6.0.4 on 2026-04-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_bitacora_observacion_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='reporte_cerrado',
            field=models.BooleanField(default=False),
        ),
    ]
