# Generated by Django 6.0.4 on 2026-06-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_alter_usuario_categoria_licencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='solicitud_correccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='estado_validacion',
            field=models.CharField(choices=[('pendiente', 'PENDIENTE'), ('validado', 'VALIDADO'), ('rechazado', 'RECHAZADO'), ('anomalia', 'ANOMALÍA')], default='validado', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='categoria_licencia',
            field=models.CharField(blank=True, choices=[('B', 'Categoría B'), ('C', 'Categoría C')], max_length=2, null=True),
        ),
    ]
