# Generated by Django 6.0.4 on 2026-05-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_bitacora_reporte_cerrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
