# Generated by Django 6.0.4 on 2026-06-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_bitacora_solicitud_correccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='mensaje_solicitud',
            field=models.TextField(blank=True, null=True),
        ),
    ]
