from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard_view, name='dashboard'),
    path('bitacora/nuevo/', views.dashboard_view, name='registro_bitacora'),
    path('vehiculo/estado/', views.dashboard_view, name='estado_vehiculo'),
    # Usuarios
    path('usuarios/', views.lista_usuarios, name='lista_usuarios'),
    path('usuarios/roles/', views.vista_roles, name='lista_roles'),
    path('usuarios/crear/', views.crear_usuario, name='crear_usuario'),
    path('usuarios/editar/<int:pk>/', views.editar_usuario, name='editar_usuario'),

    path('catalogos/vehiculos/', views.lista_vehiculos, name='lista_vehiculos'),
    path('auditoria/logs/', views.log_auditoria, name='log_auditoria'),
    path('configuracion/', views.configuracion_global, name='config_sistema'),
    path('catalogos/', views.gestion_catalogos, name='gestion_catalogos'),
    path('usuarios/roles/', views.vista_roles, name='lista_roles'),
    path('soporte/', views.vista_soporte, name='soporte'),
    path('sistema/toggle-seguro/', views.toggle_modo_seguro, name='toggle_seguro'),
    path('buscar/', views.buscar_registros, name='buscar_registros'),
    path('sistema/respaldo/', views.forzar_respaldo, name='forzar_respaldo'),
    path('catalogos/vehiculo/nuevo/', views.crear_vehiculo, name='crear_vehiculo'),
    path('catalogos/vehiculo/editar/<int:pk>/', views.editar_vehiculo, name='editar_vehiculo'),
    path('catalogos/vehiculo/eliminar/<int:pk>/', views.eliminar_vehiculo, name='eliminar_vehiculo'),
    path('admin-dashboard/', views.dashboard_admin, name='dashboard_admin'),
    path('registros/visualizacion/', views.lista_registros_all, name='registros_visualizacion'),
    path('validacion/', views.validar_registros, name='validar_registros'),
    path('validacion/cambiar-estado/<int:pk>/<str:nuevo_estado>/', views.cambiar_estado_bitacora, name='cambiar_estado'),
    path('reportes/seleccion-chofer/', views.seleccionar_chofer_reporte, name='reporte_por_chofer'),
    path('reportes/planilla-oficial/<int:chofer_id>/', views.reporte_oficial_chofer, name='planilla_oficial'),
    path('monitoreo/', views.monitoreo_tiempo_real, name='monitoreo_real'),
    path('reportes/seleccion-vehiculo/', views.seleccionar_vehiculo_reporte, name='reporte_por_vehiculo_select'),
    path('reportes/vehiculo/<int:vehiculo_id>/', views.reporte_por_vehiculo, name='planilla_vehiculo'),
    #    Activos
    path('activos/asignar/', views.crear_asignacion, name='crear_asignacion'),
    path('activos/memorandums/', views.lista_memorandums, name='lista_memorandums'),
    path('activos/historial/', views.historial_asignaciones, name='historial_asignaciones'),
    path('activos/actas/', views.lista_actas, name='lista_actas'),
    path('activos/actas/subir/<int:pk>/', views.subir_acta, name='subir_acta'),
    path('usuarios/exportar/excel/', views.exportar_usuarios_excel, name='exportar_excel'),
    path('activos/memorandum/imprimir/<int:pk>/', views.imprimir_memorandum, name='imprimir_memorandum'),
    path('activos/memorandum/ver/<int:pk>/', views.ver_memorandum, name='ver_memorandum'),
    path('activos/acta/imprimir/<int:pk>/', views.imprimir_acta_entrega, name='imprimir_acta_entrega'),
    #Bienes
    path('bienes/validar/<int:pk>/<str:estado>/', views.validar_consumo_accion, name='validar_consumo_accion'),
    path('bienes/supervision/', views.supervision_combustible, name='supervision_combustible'),
    path('bienes/validacion/', views.validacion_consumo, name='validar_consumo_bienes'),
    path('bienes/reportes/', views.reportes_bienes, name='reportes_bienes'),
    path('bienes/abastecimiento/', views.control_abastecimiento, name='control_abastecimiento'),
    path('bienes/nuevo-registro/', views.nuevo_registro_combustible, name='nuevo_registro_bienes'),
    #chofer
    path('chofer/historial/', views.historial_viajes_chofer, name='historial_chofer'),
    path('chofer/vehiculo/', views.detalle_vehiculo_chofer, name='vehiculo_chofer'),    
    path('chofer/peajes/nuevo/', views.registrar_peaje, name='registrar_peaje'),
    path('validacion/detalle/<int:bitacora_id>/', views.detalle_validacion, name='detalle_validacion'),
    path('validacion/procesar/<int:bitacora_id>/', views.procesar_validacion, name='procesar_validacion'),

    path('reportes/diario/<int:bitacora_id>/', views.reporte_diario_detallado, name='reporte_diario'),
    path('reportes/chofer/<int:chofer_id>/lista/', views.lista_reportes_chofer, name='lista_reportes_chofer'),
    path('monitoreo/detalle/<int:chofer_id>/', views.historial_diario_chofer, name='historial_diario_admin'),
    path('activos/secretarias/', views.lista_secretarias, name='lista_secretarias'),
    path('activos/secretarias/nueva/', views.crear_secretaria, name='crear_secretaria'),
    path('activos/chofer/kardex/<int:chofer_id>/', views.ver_kardex_chofer, name='kardex_chofer'),
    path('dashboard-activos/', views.dashboard_view, name='dashboard_activos'), 
    path('catalogos/vehiculo/habilitar/<int:vehiculo_id>/', views.finalizar_mantenimiento, name='finalizar_mantenimiento'),
    path('catalogos/vehiculo/mantenimiento/<int:vehiculo_id>/', views.enviar_a_mantenimiento, name='enviar_mantenimiento'),
    path('activos/baja/<int:asignacion_id>/', views.dar_baja_asignacion, name='dar_baja_asignacion'),
    path('activos/chofer/traspaso/<int:chofer_id>/', views.traspaso_secretaria, name='traspaso_secretaria'),
    path('usuarios/baja/<int:pk>/', views.dar_baja_usuario, name='dar_baja_usuario'),
    path('usuarios/reactivar/<int:pk>/', views.reactivar_usuario, name='reactivar_usuario'),
    path('usuarios/reset-password/<int:pk>/', views.reset_password_admin, name='reset_password_admin'),   
    path('sistema/backups/', views.centro_backups, name='centro_backups'),
    path('sistema/backup/total/', views.backup_total_sql, name='backup_total_sql'),
    path('catalogos/vehiculo/baja/<int:pk>/', views.dar_baja_vehiculo, name='dar_baja_vehiculo'),
    path('catalogos/vehiculo/reactivar/<int:pk>/', views.reactivar_vehiculo, name='reactivar_vehiculo'),
    path('activos/secretarias/editar/<int:pk>/', views.editar_secretaria, name='editar_secretaria'),
    path('catalogos/combustible/nuevo/', views.crear_combustible, name='crear_combustible'),
    path('catalogos/combustible/editar/<int:pk>/', views.editar_combustible, name='editar_combustible'),
    path('catalogos/combustible/vales/<int:pk>/', views.detalle_vales_combustible, name='detalle_vales_combustible'),
    path('usuarios/auditoria/<int:user_id>/', views.kardex_logs_usuario, name='kardex_logs_usuario'),
    path('sistema/enmienda/<int:pk>/', views.enmienda_bitacora_critica, name='enmienda_bitacora'),
    path('admin/enmienda/<int:pk>/', views.editar_bitacora_admin, name='editar_bitacora_admin'),
    path('catalogos/vehiculo/kardex/<int:pk>/', views.kardex_vehiculo, name='kardex_vehiculo'),
    path('chofer/mis-gastos/', views.vales_peajes_chofer, name='lista_vales_peajes'),
    path('admin/control-gastos/', views.vales_peajes_admin, name='vista_vales_peajes'),
    path('chofer/solicitar-correccion/<int:bitacora_id>/', views.solicitar_correccion, name='solicitar_correccion'),
    path('admin/solicitudes/', views.lista_solicitudes_enmienda, name='lista_solicitudes'),
    path('api/area/<int:area_id>/choferes/', views.api_choferes_por_area, name='api_choferes_area'),
    path('reportes/diario/<int:bitacora_id>/', views.reporte_diario_detalle, name='reporte_diario_detalle'),
    path('reportes/chofer/<int:chofer_id>/buscar-diario/', views.buscar_diario_por_fecha, name='buscar_diario_por_fecha'),
]

